# Update all servers of our infrastructure
- hosts: hosts_upgrades
  remote_user: <your_user>
  become: yes
  become_method: sudo

  tasks:
    - name: Ping machines before OPS
      ping:

    - name: Set timezone to Europe/Paris
      timezone:
        name: Europe/Paris

    - name: Update repositories
      apt:
        update_cache: yes

    - name: Upgrade distributions
      apt:
        name: "*"
        state: latest
      register: upgrade_result

    - name: Remove useless packages from distro's cache
      apt:
        autoclean: yes

    - name: Remove useless dependencies from distro's packages
      apt:
        autoremove: yes

    - name: Reboot servers after server's upgrades
      reboot:

#    - mail:
#        subject: "System {{ ansible_hostname }} is UP"
#      delegate_to: <mail_adress>

    - name: Ping after reboot
      ping:

    - name: Message updated packages
      mattermost:
        url: 'https://<your_domain>'
        api_key: '<key>'
        text: "{{ ansible_hostname }} ({{ inventory_hostname }}) is Alive !"
